from afs.exceptions.PtError import PtError
